export const HOME_PAGE_LOADED = 'HOME_PAGE_LOADED';
export const HOME_PAGE_UNLOADED = 'HOME_PAGE_UNLOADED';
export const UPDATE_URL = 'UPDATE_URL';
export const ADD_URL = 'ADD_URL';
export const TOPURL_PAGE_LOADED = 'TOPURL_PAGE_LOADED';
export const TOPURL_PAGE_UNLOADED = 'TOPURL_PAGE_UNLOADED';
